spring:
  config:
    import: optional:file:./.env[.properties]
  application:
    name: graduation-server
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:graduation}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  address: 0.0.0.0
  port: 8080
